// packages/svelte/src/lib/NumericText.svelte
<script lang="ts">
  import '@scritto/core';
  import { type NumericTextProps, type NumericText as NumericTextElement, BROWSER } from '@scritto/core';
  import type { HTMLAttributes } from 'svelte/elements';
  import { onMount, untrack } from 'svelte';

  const {
    value,
    trend,
    transition,
    respectMotionPreference,
    animated = true,
    ...rest
  }: NumericTextProps & HTMLAttributes<HTMLElement> = $props();

  let text = $state<NumericTextElement>()!;
  let isMounted = false;

  $effect(() => {
    text.update(
      value,
      untrack(() => isMounted && animated),
    );
  });

  $effect(() => {
    text.setOptions({ trend, transition, respectMotionPreference });
  });

  onMount(() => {
    isMounted = true;
  });
</script>

<numeric-text bind:this={text} role="img" aria-label={value} {...rest}>
  {BROWSER ? '' : value}
</numeric-text>

// packages/vue/src/NumericText.vue
<script lang="ts" setup>
import '@scritto/core';
import { type NumericTextProps, type NumericText as NumericTextElement, type Value, BROWSER } from '@scritto/core';
import { onMounted, ref, watch } from 'vue';

interface Props extends /* @vue-ignore */ NumericTextProps {
  value: Value;
}

const props = withDefaults(defineProps<Props>(), {
  animated: true,
});

const el = ref<NumericTextElement>();
let isMounted = false;

watch(
  () => props.value,
  (newValue) => {
    if (el.value) {
      el.value.update(newValue, isMounted && props.animated);
    }
  },
);

watch(
  () => [props.trend, props.transition, props.respectMotionPreference],
  () => {
    if (el.value) {
      el.value.setOptions({
        trend: props.trend,
        transition: props.transition,
        respectMotionPreference: props.respectMotionPreference,
      });
    }
  },
  { deep: true },
);

onMounted(() => {
  if (el.value) {
    el.value.setOptions({
      trend: props.trend,
      transition: props.transition,
      respectMotionPreference: props.respectMotionPreference,
    });

    el.value.update(props.value, false);
  }
  isMounted = true;
});
</script>

<template>
  <!-- @vue-expect-error types... -->
  <numeric-text
    ref="el"
    v-bind="$attrs"
    role="img"
    :aria-label="(value ?? '') + ''"
    v-html="BROWSER ? '' : (value ?? '') + ''"
  />
</template>
