// packages/solid/src/Scritto.tsx
import '@scritto/core'
import type { ScrittoProps, Scritto as ScrittoElement } from '@scritto/core'
import { createEffect, onMount, splitProps, type JSX } from 'solid-js'
import { isServer } from 'solid-js/web'

type Props = ScrittoProps & JSX.HTMLAttributes<HTMLElement>
const Scritto = (props: Props) => {
  const [p, rest] = splitProps(props, ['value', 'trend', 'transition', 'respectMotionPreference', 'bounce', 'hurry', 'animated'])

  let ref: ScrittoElement | undefined
  let isMounted = false

  createEffect(() => {
    if (ref) ref.update(p.value, isMounted && (p.animated ?? true))
  })

  createEffect(() => {
    if (ref) {
      ref.setOptions({
        trend: p.trend,
        transition: p.transition,
        respectMotionPreference: p.respectMotionPreference,
        bounce: p.bounce,
        hurry: p.hurry,
      })
    }
  })

  onMount(() => {
    isMounted = true
  })

  return (
    <scritto-text ref={ref} role="img" aria-label={p.value + ''} {...rest}>
      {isServer ? p.value : ''}
    </scritto-text>
  )
}

export default Scritto

// packages/svelte/src/lib/Scritto.svelte
<script lang="ts">
  import '@scritto/core';
  import { type ScrittoProps, type Scritto as ScrittoElement, BROWSER } from '@scritto/core';
  import type { HTMLAttributes } from 'svelte/elements';
  import { onMount, untrack } from 'svelte';

  const {
    value,
    trend,
    transition,
    respectMotionPreference,
    bounce,
    hurry,
    animated = true,
    ...rest
  }: ScrittoProps & HTMLAttributes<HTMLElement> = $props();

  let text = $state<ScrittoElement>()!;
  let isMounted = false;

  $effect(() => {
    text.update(
      value,
      untrack(() => isMounted && animated),
    );
  });

  $effect(() => {
    text.setOptions({ trend, transition, respectMotionPreference, bounce, hurry });
  });

  onMount(() => {
    isMounted = true;
  });
</script>

<scritto-text bind:this={text} role="img" aria-label={value} {...rest}>
  {BROWSER ? '' : value}
</scritto-text>
