// packages/react/src/Scritto.tsx
'use client';

import '@scritto/core';
import { type ScrittoProps, type Scritto as ScrittoElement, BROWSER } from '@scritto/core';
import { type HTMLAttributes, useLayoutEffect, useRef } from 'react';

type Props = ScrittoProps & HTMLAttributes<HTMLElement>;
const Scritto = ({ value, trend, transition, respectMotionPreference, bounce, wave, animated = true, ...rest }: Props) => {
  const ref = useRef<ScrittoElement>(null);
  const isMounted = useRef(false);

  useLayoutEffect(() => {
    if (ref.current) ref.current.update(value, isMounted.current && animated);
    if (!isMounted.current) isMounted.current = true;
  }, [value]);

  useLayoutEffect(() => {
    if (ref.current) ref.current.setOptions({ trend, transition, respectMotionPreference, bounce, wave });
  }, [trend, transition, respectMotionPreference, bounce, wave]);

  return (
    <scritto-text
      ref={ref}
      role="img"
      aria-label={value + ''}
      {...rest}
      suppressHydrationWarning
      dangerouslySetInnerHTML={{ __html: BROWSER ? '' : value }}
    />
  );
};

export default Scritto;

// packages/svelte/src/lib/Scritto.svelte
<script lang="ts">
  import '@scritto/core';
  import { type ScrittoProps, type Scritto as ScrittoElement, BROWSER } from '@scritto/core';
  import type { HTMLAttributes } from 'svelte/elements';
  import { onMount, untrack } from 'svelte';

  const {
    value,
    trend,
    transition,
    respectMotionPreference,
    bounce,
    wave,
    animated = true,
    ...rest
  }: ScrittoProps & HTMLAttributes<HTMLElement> = $props();

  let text = $state<ScrittoElement>()!;
  let isMounted = false;

  $effect(() => {
    text.update(
      value,
      untrack(() => isMounted && animated),
    );
  });

  $effect(() => {
    text.setOptions({ trend, transition, respectMotionPreference, bounce, wave });
  });

  onMount(() => {
    isMounted = true;
  });
</script>

<scritto-text bind:this={text} role="img" aria-label={value} {...rest}>
  {BROWSER ? '' : value}
</scritto-text>
