// packages/vue/src/Scritto.vue
<script lang="ts" setup>
import '@scritto/core';
import { type ScrittoProps, type Scritto as ScrittoElement, type Value, BROWSER } from '@scritto/core';
import { onMounted, ref, watch } from 'vue';

interface Props extends /* @vue-ignore */ ScrittoProps {
  value: Value;
}

const props = withDefaults(defineProps<Props>(), {
  animated: true,
});

const el = ref<ScrittoElement>();
let isMounted = false;

watch(
  () => props.value,
  (newValue) => {
    if (el.value) {
      el.value.update(newValue, isMounted && props.animated);
    }
  },
);

watch(
  () => [props.trend, props.transition, props.respectMotionPreference, props.bounce],
  () => {
    if (el.value) {
      el.value.setOptions({
        trend: props.trend,
        transition: props.transition,
        respectMotionPreference: props.respectMotionPreference,
        bounce: props.bounce,
      });
    }
  },
  { deep: true },
);

onMounted(() => {
  if (el.value) {
      el.value.setOptions({
        trend: props.trend,
        transition: props.transition,
        respectMotionPreference: props.respectMotionPreference,
        bounce: props.bounce,
      });

    el.value.update(props.value, false);
  }
  isMounted = true;
});
</script>

<template>
  <scritto-text
    ref="el"
    v-bind="$attrs"
    role="img"
    :aria-label="(value ?? '') + ''"
    v-html="BROWSER ? '' : (value ?? '') + ''"
  />
</template>

// packages/svelte/src/lib/Scritto.svelte
<script lang="ts">
  import '@scritto/core';
  import { type ScrittoProps, type Scritto as ScrittoElement, BROWSER } from '@scritto/core';
  import type { HTMLAttributes } from 'svelte/elements';
  import { onMount, untrack } from 'svelte';

  const {
    value,
    trend,
    transition,
    respectMotionPreference,
    bounce,
    animated = true,
    ...rest
  }: ScrittoProps & HTMLAttributes<HTMLElement> = $props();

  let text = $state<ScrittoElement>()!;
  let isMounted = false;

  $effect(() => {
    text.update(
      value,
      untrack(() => isMounted && animated),
    );
  });

  $effect(() => {
    text.setOptions({ trend, transition, respectMotionPreference, bounce });
  });

  onMount(() => {
    isMounted = true;
  });
</script>

<scritto-text bind:this={text} role="img" aria-label={value} {...rest}>
  {BROWSER ? '' : value}
</scritto-text>
